
spring:
     application:
          name: spirng-boot-rabbitmq
server:
     port: 8081

rocketmq:
      namesrvAddr: 10.5.41.64:9876
      consumer:
          consumerGroup: Push_Consumer
      producer: 
          producerGroup: gaoweigang